image: adstewart/dafny-gitpod:latest

vscode:
  extensions:
    - https://github.com/dafny-lang/ide-vscode/releases/download/v2.3.0/ide-vscode-2.3.0.vsix

tasks:
  - init: git config --global alias.slog 'log --pretty=oneline --abbrev-commit'
  - init: git config --global alias.co checkout
  - command: curl https://raw.githubusercontent.com/dafny-lang/dafny/master/docs/OnlineTutorial/guide.md > guide.md && gp open guide.md


